---
title: "R Notebook"
output: html_notebook
---

It's time to get in to classification <br>

libraries:
```{r eval=FALSE, include=FALSE}
install.packages("rpart")
install.packages("randomForest")
install.packages("e1071")

```

```{r}
library("rpart", lib.loc="~/R/R-3.5.1/library")
library("randomForest", lib.loc="~/R/R-3.5.1/library")
library("e1071", lib.loc="~/R/R-3.5.1/library")

```

<h4>Decision tree</h4>

```{r}
#Clasification
data(kyphosis)

fit <- rpart(Kyphosis ~ Age + Number + Start,
             method="class", data=kyphosis)

printcp(fit)
plotcp(fit) 
summary(fit)

plot(fit, uniform=TRUE, main="Classification Tree for Kyphosis") 

text(fit, use.n=TRUE, all=TRUE, cex=.8)
```

```{r}
#Regression
data(cu.summary)

fit <- rpart(Mileage~Price + Country + Reliability + Type, 
             method="anova", data=cu.summary)

printcp(fit) 
plotcp(fit)
summary(fit) 


par(mfrow=c(1,2))
rsq.rpart(fit)

plot(fit, uniform=TRUE, 
     main="Regression Tree for Mileage ")
text(fit, use.n=TRUE, all=TRUE, cex=.6)

```

<h4>Random forrest</h4>

```{r}
set.seed(1)

data("iris")

iris.rf <- randomForest(iris[,-5], iris[,5], proximity=TRUE)
plot(outlier(iris.rf), type="h", col=c("red", "green", "blue")[as.numeric(iris$Species)])

MDSplot(iris.rf, iris$Species, palette=rep(1, 3), pch=as.numeric(iris$Species))
```

<h4>Support Vector Machine</h4>

```{r}

```





