---
title: "ggplot"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---


Libraries:
```{r eval=FALSE, include=FALSE}
install.packages("ggplot2")
install.packages("tidyr")
install.packages("rvest")
install.packages("RColorBrewer")
install.packages("grid")

```

```{r}
library("ggplot2", lib.loc="~/R/R-3.5.1/library")
library("tidyr", lib.loc="~/R/R-3.5.1/library")
library("rvest", lib.loc="~/R/R-3.5.1/library")
library("RColorBrewer", lib.loc="~/R/R-3.5.1/library")
library("grid", lib.loc="~/R/R-3.5.1/library")

```

Lets start
```{r}
#Polution data.  number/percent
tdist <- read_html("https://en.wikipedia.org/wiki/List_of_countries_by_carbon_dioxide_emissions")
pdata <- tdist %>% html_node("table.wikitable") %>% html_table()
pdata <- pdata[2:53, 1:3]

```

```{r}
##simpele functie
#qplot(x,y,data,geom)
attach(pdata)
qplot(x = Country, y = `Fossil fuel CO2 emissions (kt) in 2015[8]`, data = head(pdata), geom = "point")

#llets try the same visualisation, but with the ggplot function
ggplot(head(pdata), aes(Country, `Fossil fuel CO2 emissions (kt) in 2015[8]`)) + geom_point()

detach(pdata)
```

The ggplot function is is a lot versitiler than the qplot function, so that's what were mostly gone use.

To make it easy I'm gone folow this: http://r-statistics.co/Complete-Ggplot2-Tutorial-Part1-With-R-Code.html

```{r}
midwest <- midwest
attach(midwest)
g <- ggplot(midwest, aes(x=area, y=poptotal)) + geom_point() + geom_smooth(method="glm") 
g
g <- g + xlim(c(0, 0.1)) + ylim(c(0, 1000000)) #setting a limid
g
g1 <- g + coord_cartesian(xlim=c(0,0.1), ylim=c(0, 1000000)) #zoom in
g1 <- g1 + labs(title="Area Vs Population", subtitle="From midwest dataset", y="Population", x="Area", caption="Midwest Demographics")                    #titel and labels
g1






detach(midwest)
```

```{r}
gg <- ggplot(midwest, aes(x=area, y=poptotal)) + 
  geom_point(col="steelblue", size=3) +   # Set static color and size for points
  geom_smooth(method="lm", col="firebrick") +  # change the color of line
  coord_cartesian(xlim=c(0, 0.1), ylim=c(0, 1000000)) + 
  labs(title="Area Vs Population", subtitle="From midwest dataset", y="Population", x="Area", caption="Midwest Demographics")
gg

gg2 <- ggplot(midwest, aes(x=area, y=poptotal)) + 
  geom_point(aes(col=state), size=3) +  # Set color to vary based on state categories.
  geom_smooth(method="lm", col="firebrick", size=2) + 
  coord_cartesian(xlim=c(0, 0.1), ylim=c(0, 1000000)) + 
  labs(title="Area Vs Population", subtitle="From midwest dataset", y="Population", x="Area", caption="Midwest Demographics")
gg2
gg2 + theme(legend.position="None")       #remove legend
gg2 <- gg2 + scale_colour_brewer(palette = "Set1")      #change color palette
gg2

```

```{r}
#for more colors
library("RColorBrewer", lib.loc="~/R/R-3.5.1/library")
head(brewer.pal.info, 10)
```

```{r}
#Our base plot
gg <- ggplot(midwest, aes(x=area, y=poptotal)) + 
  geom_point(aes(col=state), size=3) +  # Set color to vary based on state categories.
  geom_smooth(method="lm", col="firebrick", size=2) + 
  coord_cartesian(xlim=c(0, 0.1), ylim=c(0, 1000000)) + 
  labs(title="Area Vs Population", subtitle="From midwest dataset", y="Population", x="Area", caption="Midwest Demographics")
gg

# Change Axis Texts
#look out with dates: scale_x_date
gg <- gg + scale_y_continuous(breaks=seq(0, 1000000, 200000), labels = function(x){paste0(x/1000, 'K')})
gg

```

On to the big stuf

```{r}
#base
options(scipen=999)
data("midwest")
theme_set(theme_bw())

gg <- ggplot(midwest, aes(x=area, y=poptotal)) + 
  geom_point(aes(col=state, size=popdensity)) + 
  geom_smooth(method="loess", se=F) + xlim(c(0, 0.1)) + ylim(c(0, 500000)) + 
  labs(title="Area Vs Population", y="Population", x="Area", caption="Source: midwest")
gg

```

```{r}
#modifying visuals
gg + theme(plot.title=element_text(size=20, 
                                    face="bold", 
                                    color="tomato",
                                    hjust=0.5,
                                    lineheight=1.2),  # title
            plot.subtitle=element_text(size=15, 
                                       face="bold",
                                       hjust=0.5),  # subtitle
            plot.caption=element_text(size=15),  # caption
            axis.title.x=element_text(vjust=10,  
                                      size=15),  # X axis title
            axis.title.y=element_text(size=15),  # Y axis title
            axis.text.x=element_text(size=10, 
                                     angle = 30,
                                     vjust=.5),  # X axis text
            axis.text.y=element_text(size=10))  # Y axis text
```

```{r}
#annotations
attach(midwest)

gg + geom_text(aes(label=county), size=2, data=midwest) + labs(subtitle="With ggplot2::geom_text") + theme(legend.position = "None")

midwest_sub <- midwest[midwest$poptotal > 300000, ]
midwest_sub$large_county <- ifelse(midwest_sub$poptotal > 300000, midwest_sub$county, "")

gg <- gg + geom_text(aes(label=large_county), size=2, data=midwest_sub) + labs(subtitle="With ggplot2::geom_text") + theme(legend.position = "None")
gg

library(grid)
my_text <- "This text is at x=0.7 and y=0.8!"
my_grob = grid.text(my_text, x=0.7,  y=0.8, gp=gpar(col="firebrick", fontsize=10, fontface="bold"))
gg <- gg + annotation_custom(my_grob)
gg

detach(midwest)

```

What do I still miss after this:
        - rightsided axes
        - stats


